version: '3.8'

services:
  moodle:
    image: bitnami/moodle:latest
    ports:
      - "8080:8080"        # Mapea el puerto 8080 de Moodle al host
    volumes:
      - moodle_data:/bitnami/moodle  # Datos de Moodle
    environment:
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle_user
      - MOODLE_DATABASE_PASSWORD=moodle_password
      - ALLOW_EMPTY_PASSWORD=no  # Seguridad adicional
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql  # Datos de MySQL
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle_user
      - MYSQL_PASSWORD=moodle_password

volumes:
  moodle_data:
  db_data:

